<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <p><?php echo $this->__("Você será redirecionado ao PagSeguro após a confirmação do pedido.") ?></p>
        <img src="<?php echo $this->getSkinUrl('images/pagseguro/pagseguro.jpg'); ?>" alt="<?php echo $this->getMethodCode() ?>" title="<?php echo $this->getMethodCode() ?>" />
    </li>
</ul>